import React from 'react'

const AboutDeals = () => {
  return (
    <div className="lg:max-w-[1140px] md:max-w-[720px] max-w-[540px] mx-auto py-[36px] px-[14px] text-[#373737]">
        <h1 className='mb-[12px] font-bold'>Today’s Deals That Will Make You Smile</h1>
        <p className='text-[14px] mb-[12px]'>Shopping on your mind? So why not get the best deals on time? Be it any day or any time of the week, the best deals on the internet will leave you gaga over it. Shopping online is simple and fun, and here we are, to spread smiles with nothing but the best deals online. You name it, we have it - from fashion to foot wear, electronics to home and kitchen appliances, and more and more. What are the best deals today? We’ve got a list of all the top and exclusive deals for you to pick from a wide range of products like electronics, laptops, mobile phones, smart gadgets, TVs, sarees, stylish tops for men, women, kids, etc, etc, etc… And our list goes on and on. Get the best deals at unbelievable prices from the best shopping sites like Amazon, Myntra, Flipkart, Tata Cliq and many more. We’ve got some amazing discounts of up to 80% to help you Save On Everything. What are you waiting for? Fill in your shopping list now.</p>
        <h1 className='font-bold text-[18px] text-[#16171a] mb-[12px]'>Best Of Flipkart, Pepperfry, Croma & Dell</h1>
        <p className='text-[14px] mb-[12px]'>We’ve handpicked some of the coolest deals from a variety of online stores and portals like Flipkart, Pepperfry, Croma, Dell and others just to make your shopping experience more fun and exciting. The deals are curated just for you. If you are a gadget freak, or a fashionista, or someone who is planning to buy something online, we’ve got everything covered for you. Get exclusive deals on laptops, desktops, workstations, wireless headphones, and other accessories from Dell and Croma. What else? Avail discounts upto 80% and more, on a wide range of products. Aren’t these some cool deals available online?</p>
        <h1 className='font-bold text-[18px] text-[#16171a] mb-[12px]'>Fashion Deals From AJIO, Amazon, Myntra, & More In Today’s Best Deals</h1>
        <p className='text-[14px] mb-[12px]'>Shopping is a therapy and when you get some best deals from renowned brands and online stores, it does give you a sense of satisfaction. Whether you are looking for cool, trendy, traditional or western wear for men, women or kids, we’ve got you covered already. Women, get ready to shop, and get the best deals on sarees, jewellery, hand bags, etc at the right prices. Men, do not be disheartened, we’ve got some super cool graphic and designer T-shirts, classy shirts, trousers, watches, etc to help you make the perfect fashion statement. Footwear for men and women - formal shoes, sports shoes, boots, sandals, flip flops, etc are also in the offering at affordable prices on AJIO. And sunglasses, are we not talking about this? Yes, we are. Wear those aviators, or put on the retro sunglasses and make the perfect style statement. If you are a travel freak, we got exclusive deals on Amazon for all your travel related accessories like backpacks, rucksacks, neck pillows, duffle bags, document organizers, bottles, etc. You also get to avail the latest and best offers in the town for all your cosmetics, hair straighteners, and etc on Flipkart, Snapdeal etc. So why not make the best of online shopping today.</p>
        <h1 className='font-bold text-[18px] text-[#16171a] mb-[12px]'>Best Deals - Big Savings - Best Quality</h1>
        <p className='text-[14px]'>Get the best deals and save big on all your purchases. We do not offer products that are not only affordable but are the best in quality and style. Now, end your long wait of buying a TV set, a home theatre or even a smartphone you’ve been dreaming of buying. Get a list of the best deals on wireless earphones, portable Bluetooth speakers, power banks, hard disks, washing machines, ACs, etc. Our deals are going to leave you surprised for sure. For those planning to give their home a new look, we have some classy and elegant looking door and window curtains, carpets, coffee tables, bean bags, sofas, wall decor, etc that will add life to your living spaces. Get the perfect gifts for your loved ones with the best offers in today’s deals on Amazon India. So, everything we’ve been talking about, can be the perfect gifting idea to spread smiles. Our list also includes discounts on rings for men and women. Perfect to gift one for yourself or someone dear to you.</p>
        <p className='text-[14px] mb-[12px]'>If you are a fitness freak, why not buy those shoes, track pants, or those fitness tracks in today{"'"}s best deals? What if we told you about the 60% discount you get on these? Sounds a great deal, right? Water bottles for your gym needs, lunch boxes to pack your healthy snacks, or a pair of perfect gloves, etc are also in the list of today’s best deals. These are just a few we could list out, but the more you search for, the better the results are going to be, and so will your savings. Why wait more when you can GrabOn to these best deals on the internet? Fill Your Cart. Happy Deals! Happy Shopping!</p>
    </div>
  )
}

export default AboutDeals